### ISSUE TITLE
Major Reference Guide Restructuring/Refactoring [4.0]

### ISSUE THREAD

**Issue by idugalic** [AxonIQ/reference-guide#44] opened 2018-12-19 10:31 UTC

**Comment by smcvb** [comment] 2018-12-19 11:04
Sorry, I only just now notice we already have an issue which should/could serve as an Epic...
I'll mark this as a duplicate of ticket #6. Again, sorry for the effort @idugalic!

**Closed by smcvb** 2018-12-19 11:04 UTC
Labels: Epic
